Split ci_build.sh to be part of the repo.
Minimizing what has to happen out of source control in (e.g.) the post-receive
hook.

diff --git a/extra/git/post-receive b/extra/git/post-receive
--- a/extra/git/post-receive
+++ b/extra/git/post-receive
@@ -14,23 +14,13 @@ KEROUAC=${KEROUAC:-""}
 # environment)                                                                 #
 ################################################################################
 
-MAIL_TO=${MAIL_TO:-""}
-# MAIL_TO="person1@example.com person2@example.com"
-
-MAIL_CMD=${MAIL_CMD:-"/usr/bin/env mail"}
-
-NOTIFY_ON=${NOTIFY_ON:-"FAILURE"}
-# NOTIFY_ON="ALL"
-
-KEROUAC_CONFIG_NAME=${KEROUAC_CONFIG_NAME:-"kerouac.json"}
+CI_SCRIPT=${CI_SCRIPT:-"ci_build.sh"}
 
 BATCH=${BATCH:-"/usr/bin/env batch"}
 
-BASH=${BASH:-"/usr/bin/env bash"}
-
 GIT=${GIT:-"/usr/bin/env git"}
 
-GIT_LOG_CMD=${GIT_LOG_CMD:-"log --name-status -n1"}
+GIT_LOG_CMD=${GIT_LOG_CMD:-"log --name-status"}
 
 #############################
 # Verify required variables #
@@ -53,62 +43,6 @@ then
     echo "Please edit hook / env to set KEROUAC"
     exit 1
 fi
-
-##########################################################
-# Functions to split out some of the gnarly build stuff. #
-##########################################################
-
-function create_build_file {
-    echo_build
-    echo_log_output
-    echo_notification
-    # Note that the bash file doing the build cleans up itself and the log file
-    # it references.
-    echo_cleanup
-}
-
-function echo_build {
-    echo "$KEROUAC build $TMP_BUILD_DIR $TMP_BUILD_DIR/$KEROUAC_CONFIG_NAME $KEROUAC_ROOT $PROJECT $TAG" >> $BUILD_FILE
-    echo 'if [ $? != "0" ]; then STATUS=FAILED; else STATUS=SUCCEEDED; fi' >> $BUILD_FILE
-}
-
-function echo_log_output {
-    echo "echo >> $LOG_FILE" >> $BUILD_FILE
-    echo "echo 'Kerouac log output:' >> $LOG_FILE" >> $BUILD_FILE
-    echo "cat \$($KEROUAC print kerouaclogpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
-
-    echo "echo >> $LOG_FILE" >> $BUILD_FILE
-    echo "echo 'Build stdout:' >> $LOG_FILE" >> $BUILD_FILE
-    echo "cat \$($KEROUAC print stdoutpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
-
-    echo "echo >> $LOG_FILE" >> $BUILD_FILE
-    echo "echo 'Build stderr:' >> $LOG_FILE" >> $BUILD_FILE
-    echo "cat \$($KEROUAC print stderrpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
-}
-
-function echo_cleanup {
-    echo "rm $LOG_FILE" >> $BUILD_FILE
-    echo "rm $BUILD_FILE" >> $BUILD_FILE
-}
-
-function echo_notification {
-    if [ "$MAIL_TO" != "" ]
-    then
-        if [ $NOTIFY_ON == "FAILURE" ] || [ $NOTIFY_ON == "ALL" ]
-        then
-            echo 'if [ $STATUS == "FAILED" ]; then' >> $BUILD_FILE
-            echo "cat $LOG_FILE | $MAIL_CMD -s 'Build $TAG failed' $MAIL_TO" >> $BUILD_FILE
-            echo 'fi' >> $BUILD_FILE
-        fi
-
-        if [ $NOTIFY_ON == "ALL" ]
-        then
-            echo 'if [ $STATUS == "SUCCEEDED" ]; then' >> $BUILD_FILE
-            echo "cat $LOG_FILE | $MAIL_CMD -s 'Build $TAG succeeded' $MAIL_TO" >> $BUILD_FILE
-            echo 'fi' >> $BUILD_FILE
-        fi
-    fi
-}
 
 ################################
 # Begin actual hook processing #
@@ -143,13 +77,19 @@ do
     $GIT checkout $BRANCH
     $GIT reset --hard $TO
 
-    BUILD_FILE=$(mktemp)
     LOG_FILE=$(mktemp)
 
-    $GIT $GIT_LOG_CMD $TO > $LOG_FILE
+    $GIT $GIT_LOG_CMD $FROM..$TO > $LOG_FILE
 
-    # Construct a bash script to be run in batch.
-    create_build_file
+    CI_COMMAND="$TMP_BUILD_DIR/$CI_SCRIPT"
 
-    echo "$BASH $BUILD_FILE" | $BATCH
+    if [ ! -x "$CI_COMMAND" ]
+    then
+        echo "ERROR: $CI_COMMAND does not exist or is not executable."
+        exit 1
+    fi
+
+    RUN_CI_COMMAND="$CI_COMMAND $KEROUAC $KEROUAC_ROOT $PROJECT $TAG $LOG_FILE"
+
+    echo "$RUN_CI_COMMAND" | $BATCH
 done
