Clean up post-receive hook.

diff --git a/extra/git/post-receive b/extra/git/post-receive
--- a/extra/git/post-receive
+++ b/extra/git/post-receive
@@ -54,6 +54,64 @@ then
     exit 1
 fi
 
+##########################################################
+# Functions to split out some of the gnarly build stuff. #
+##########################################################
+
+function create_build_file {
+    echo_build
+    echo_notification
+    # Note that the bash file doing the build cleans up itself and the log file
+    # it references.
+    echo_cleanup
+}
+
+function echo_build {
+    echo "$KEROUAC build $TMP_BUILD_DIR $TMP_BUILD_DIR/$KEROUAC_CONFIG_NAME $KEROUAC_ROOT $PROJECT $TAG" >> $BUILD_FILE
+
+    echo 'if [ $? != "0" ]; then STATUS=FAILED; else STATUS=SUCCEEDED; fi' >> $BUILD_FILE
+}
+
+function echo_log_output {
+    echo "echo >> $LOG_FILE" >> $BUILD_FILE
+    echo "echo 'Kerouac log output:' >> $LOG_FILE" >> $BUILD_FILE
+    echo "cat \$($KEROUAC print kerouaclogpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
+
+    echo "echo >> $LOG_FILE" >> $BUILD_FILE
+    echo "echo 'Build stdout:' >> $LOG_FILE" >> $BUILD_FILE
+    echo "cat \$($KEROUAC print stdoutpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
+
+    echo "echo >> $LOG_FILE" >> $BUILD_FILE
+    echo "echo 'Build stderr:' >> $LOG_FILE" >> $BUILD_FILE
+    echo "cat \$($KEROUAC print stderrpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
+}
+
+function echo_cleanup {
+    echo "rm $LOG_FILE" >> $BUILD_FILE
+    echo "rm $BUILD_FILE" >> $BUILD_FILE
+}
+
+function echo_notification {
+    echo_log_output
+
+    if [ "$MAIL_TO" != "" ]
+    then
+        if [ $NOTIFY_ON == "FAILURE" ] || [ $NOTIFY_ON == "ALL" ]
+        then
+            echo 'if [ $STATUS == "FAILED" ]; then' >> $BUILD_FILE
+            echo "cat $LOG_FILE | $MAIL_CMD -s 'Build $TAG failed' $MAIL_TO" >> $BUILD_FILE
+            echo 'fi' >> $BUILD_FILE
+        fi
+
+        if [ $NOTIFY_ON == "ALL" ]
+        then
+            echo 'if [ $STATUS == "SUCCEEDED" ]; then' >> $BUILD_FILE
+            echo "cat $LOG_FILE | $MAIL_CMD -s 'Build $TAG succeeded' $MAIL_TO" >> $BUILD_FILE
+            echo 'fi' >> $BUILD_FILE
+        fi
+    fi
+}
+
 ################################
 # Begin actual hook processing #
 ################################
@@ -65,8 +123,6 @@ mkdir -p $KEROUAC_WORK_DIR
 
 HOLD_GIT_DIR="$GIT_DIR"
 BASE_DIR=$(pwd)
-
-# TODO: allow only the last "to" pushed per ref to be built
 
 while read LINE
 do
@@ -87,7 +143,6 @@ do
     cd $TMP_BUILD_DIR
     unset GIT_DIR
     $GIT checkout $BRANCH
-    echo "reset"
     $GIT reset --hard $TO
 
     BUILD_FILE=$(mktemp)
@@ -96,44 +151,7 @@ do
     $GIT $GIT_LOG_CMD $TO > $LOG_FILE
 
     # Construct a bash script to be run in batch.
-
-    echo "$KEROUAC build $TMP_BUILD_DIR $TMP_BUILD_DIR/$KEROUAC_CONFIG_NAME $KEROUAC_ROOT $PROJECT $TAG" >> $BUILD_FILE
-
-    echo 'if [ $? != "0" ]; then STATUS=FAILED; else STATUS=SUCCEEDED; fi' >> $BUILD_FILE
-
-    echo "echo >> $LOG_FILE" >> $BUILD_FILE
-    echo "echo 'Kerouac log output:' >> $LOG_FILE" >> $BUILD_FILE
-    echo "cat \$($KEROUAC print kerouaclogpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
-
-    echo "echo >> $LOG_FILE" >> $BUILD_FILE
-    echo "echo 'Build stdout:' >> $LOG_FILE" >> $BUILD_FILE
-    echo "cat \$($KEROUAC print stdoutpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
-
-    echo "echo >> $LOG_FILE" >> $BUILD_FILE
-    echo "echo 'Build stderr:' >> $LOG_FILE" >> $BUILD_FILE
-    echo "cat \$($KEROUAC print stderrpath $KEROUAC_ROOT $PROJECT $TAG) >> $LOG_FILE" >> $BUILD_FILE
-
-    if [ "$MAIL_TO" != "" ]
-    then
-        if [ $NOTIFY_ON == "FAILURE" ] || [ $NOTIFY_ON == "ALL" ]
-        then
-            echo 'if [ $STATUS == "FAILED" ]; then' >> $BUILD_FILE
-            echo "cat $LOG_FILE | $MAIL_CMD -s 'Build $TAG failed' $MAIL_TO" >> $BUILD_FILE
-            echo 'fi' >> $BUILD_FILE
-        fi
-
-        if [ $NOTIFY_ON == "ALL" ]
-        then
-            echo 'if [ $STATUS == "SUCCEEDED" ]; then' >> $BUILD_FILE
-            echo "cat $LOG_FILE | $MAIL_CMD -s 'Build $TAG succeeded' $MAIL_TO" >> $BUILD_FILE
-            echo 'fi' >> $BUILD_FILE
-        fi
-    fi
-
-    # Note that the bash file doing the build cleans up itself and the log file
-    # it references.
-    echo "rm $LOG_FILE" >> $BUILD_FILE
-    echo "rm $BUILD_FILE" >> $BUILD_FILE
+    create_build_file
 
     echo "$BASH $BUILD_FILE" | $BATCH
 done
